### ISSUE TITLE
Test succeeds but lot many "INFO: failed to connect to receiver" messages printed 

### ISSUE THREAD

**Issue by santoshx** [Microsoft/ntttcp-for-linux#22]
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5114 on socket[187]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5115 on socket[189]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5115 on socket[189]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5116 on socket[189]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5116 on socket[189]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5116 on socket[191]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5117 on socket[192]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5117 on socket[192]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5118 on socket[192]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5118 on socket[192]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5118 on socket[192]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5119 on socket[195]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5119 on socket[196]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5120 on socket[197]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5120 on socket[197]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5121 on socket[199]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5121 on socket[199]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5122 on socket[201]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5122 on socket[202]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5123 on socket[203]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5123 on socket[203]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5124 on socket[205]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5124 on socket[205]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5125 on socket[207]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5125 on socket[207]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5126 on socket[209]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5126 on socket[209]. return = -1, errno = 111
02:13:18 INFO: failed to connect to receiver: 192.168.0.200:5127 on socket[211]. return = -1, errno = 111

**Comment by santoshx** [comment]
I used latest tip of this repo:
cfd0a96cc7c4ef0add8dafea4765467b6ca3ab25

Receiver  (RH7.5):
$ntttcp -P 256 -t 300 -e -W 1 -C 1 -r 192.168.0.200 -H

Sender (RH6.10):
ntttcp -P128 -t 300 -e -W 1 -C 1 -s 192.168.0.200

**Comment by milpita** [comment]
-P 256 (server), -P 126 (client) works, with 127+ it fails.

**Comment by santoshx** [comment]
@milpita  Can you try PR #24 ?

**Comment by simonxiaoss** [comment]
if you see "too many open files", then it reached the system limits and you need to increase the limit by ulimit -n to a larger value.

**Comment by santoshx** [comment]
Ok understood
