### ISSUE TITLE
nttcp Receive: "failed to bind the socket to local address  errcode = -1. errcode = 98" Errors

### ISSUE THREAD

**Issue by krishneil** [Microsoft/ntttcp-for-linux#4]
Hi 

Hi am seeing "Failed to bind the Socket to Local Address  errcode = -1. errcode = 98" errors when trying to start as a receiver on a RHEL 7.3 OS. I have tried binding to all IP's as well a single IP and with default and single threads.

is there something needed or option i need to enable to get this to work ?  

using Default:

/opt/ntttcp-for-linux/src> ./ntttcp -r -V
NTTTCP for Linux 1.2.0
---------------------------------------------------------
*** receiver role
threads:                         16
cpu affinity:                    *
server address:                  0.0.0.0
domain:                          IPv4
protocol:                        TCP
server port starting at:         5001
receiver socket buffer (bytes):  65536
test duration (sec):             60
show system tcp retransmit:      no
verbose mode:                    enabled
---------------------------------------------------------
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5004
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5007
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5002
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5003
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5001
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5005
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5008
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5006
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5011
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5009
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5010
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5012
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5014
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5013
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5015
10:41:05 DBG : ntttcp server is listening on 0.0.0.0:5016
10:41:05 DBG : 17 threads created
10:41:05 DBG : failed to bind the socket to local address: 0.0.0.0 on socket: 19. errcode = -1. errcode = 98
10:41:05 ERR : cannot bind the socket on address: 0.0.0.0

using Single Thread:
/opt/ntttcp-for-linux/src> ./ntttcp -r -m 1 -V
NTTTCP for Linux 1.2.0
---------------------------------------------------------
*** receiver role
threads:                         1
cpu affinity:                    *
server address:                  0.0.0.0
domain:                          IPv4
protocol:                        TCP
server port starting at:         5001
receiver socket buffer (bytes):  65536
test duration (sec):             60
show system tcp retransmit:      no
verbose mode:                    enabled
---------------------------------------------------------
10:42:35 DBG : 2 threads created
10:42:35 DBG : failed to bind the socket to local address: 0.0.0.0 on socket: 3. errcode = -1. errcode = 98
10:42:35 DBG : ntttcp server is listening on 0.0.0.0:5001
10:42:35 ERR : cannot bind the socket on address: 0.0.0.0

OS Details:
Red Hat Enterprise Linux Server 7.3 (Maipo)
uname -a
Linux  3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by simonxiaoss** [comment]
Error code 98 means the address is already in use. Can you check the port of that socket is not being used before running ntttcp?
Please note: by default, ntttcp will use port 5000 as sync port.

**Comment by krishneil** [comment]
It looked like i had xinetd service running for netperf and it also seems to use port 5000. used -p option to use different ports and am able to pass traffic now. Thank you. This issues can be closed.
