### ISSUE TITLE
Receiver stuck forever from the beginning when running UDP protocol in no-sync mode (no issue in sync mode)

### ISSUE THREAD

**Issue by wilsonNg007** [microsoft/ntttcp-for-linux#57]
ntttcp for linux version: 1.4.0 (latest)

**Cmdlines:**
Sender:  ntttcp -s -m 1,*,<receiver IP> -u -V -t 30 -b 1470 -N   # or any -b <buffer length>
Receiver:  ntttcp -r -m 1,*,<receiver IP> -u -V -t 30 -N

Sender will completed with output indicating the throughput, cycles/byte, time, etc.

However, the receiver just stuck forever from the beginning (last message: "INFO: 1 threads created").

No issue in TCP protocol (sync/no-sync), and no issue in UDP sync mode.

**Impact:**
We have use case using Windows as ntttcp sender (and Linux as ntttcp receiver), and only no-sync mode is supported in ntttcp between windows and linux.

**Comment by wilsonNg007** [comment]
@simonxiaoss , @glima -- could you or someone help look at this issue?  Thanks.

**Comment by wilsonNg007** [comment]
The issue looks like the receiver did not receive any connection request from the sender, and just keep waiting forever.

**Comment by santoshx** [comment]
@wilsonNg007 I posted a possible fix for this issue: https://github.com/microsoft/ntttcp-for-linux/pull/61

**Comment by santoshx** [comment]
Fixed by PR https://github.com/microsoft/ntttcp-for-linux/pull/61 . Closing this issue.
