### ISSUE TITLE
What is the difference between synch and no-synch mode?

### ISSUE THREAD

**Issue by jefjos** [microsoft/ntttcp-for-linux#73]

**Comment by simonxiaoss** [comment]
In no_synch mode, sender will not communicate with receiver to negotiate the test parameters. The test traffic will be started immediately.
The main purpose of this no_synch mode is to interop with Windows ntttcp (in its no_sync mode too). 
Windows ntttcp has "complex" synch mode and ntttcp-for-linux does not want to support that.
